### ISSUE TITLE
Bypass watchdog for long dns resolution

### ISSUE THREAD

**Issue by droscy** [droscy/esphome#3]
The DNS resolution that happens in `esp_wireguard_peer_init()` can take long enough on some network setups to trigger the task watchdog timeout panic. I saw that esphome's OTA component seems to have dealt with the same issue, temporarily raising the timeout value for a long operation and bringing it back down after. I'm wondering if this is too much of an edge case to get an "official" fix or if it's worth looking into.

See second report here https://github.com/esphome/esphome/pull/4256#issuecomment-1565547581

@thomas0bernard this issue for your second report.

**Comment by thomas0bernard** [comment]
For esp-idf I just added `CONFIG_ESP_TASK_WDT_TIMEOUT_S=10` to the build config and it was fine, albeit a bit of a dirty fix. Doesn't seem to be that easy for Arduino... I'll try to come up with a cleaner solution in a PR later this week.

**Comment by lhoracek** [comment]
I would leave this for later development as it is something that requires quite low level change.

**Comment by thomas0bernard** [comment]
Came up with a bit of a cleaner solution in PR #5.

**Comment by droscy** [comment]
I don't know how to slow down my DNS to trigger the watchdog, but the code looks good and my tests succeeded. Many thanks.

Just one tip, I changed

    wdtc.timeout_ms = CONFIG_ESP_TASK_WDT_TIMEOUT_S;

to

    wdtc.timeout_ms = CONFIG_ESP_TASK_WDT_TIMEOUT_S * 1000;

because it should be in milliseconds. Is that right?

Don't you mind if I wrap it in two functions `suspend_wdt()` and `resume_wdt()` for easier code reading? Please test them. Thanks.

**Comment by droscy** [comment]
I cannot push to your branch, so test it using mine `fix/wg/dns-wdt`. Thanks.

**Comment by droscy** [comment]
Many thanks @thomas0bernard, I've just merged your PR.
